### ISSUE TITLE
3.0-alpha2: Unhandled exception regarding a bad request to elasticsearch

### ISSUE THREAD

**Issue by funkyfuture** [kitodo/kitodo-production#1859]
steps to reproduce:

- setup kitodo, mysql and elasticsearch as described in the wiki
- additionally `curl -s -X PUT "http://elasticsearch:9200/kitodo"` when `curl http://elasticsearch:9200/kitodo` yields a 404
- login with the test account
- open `http://localhost:8080/kitodo/pages/processes.jsf` in a web browser

results in:

```
[ERROR] 2018-10-02 15:49:42.804 [http-nio-8080-exec-10] BatchForm - org.elasticsearch.client.ResponseException: GET http://elasticsearch:9200/kitodo/process/_search?pretty=true&from=0&size=500: HTTP/1.1 400 Bad Request
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "No mapping found for [creationDate] in order to sort on",
        "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
        "index" : "kitodo"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "kitodo",
        "node" : "JTrmz0_SRU2cNG-iyouvKw",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "No mapping found for [creationDate] in order to sort on",
          "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
          "index" : "kitodo"
        }
      }
    ]
  },
  "status" : 400
}

org.kitodo.data.exceptions.DataException: org.elasticsearch.client.ResponseException: GET http://elasticsearch:9200/kitodo/process/_search?pretty=true&from=0&size=500: HTTP/1.1 400 Bad Request
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "No mapping found for [creationDate] in order to sort on",
        "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
        "index" : "kitodo"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "kitodo",
        "node" : "JTrmz0_SRU2cNG-iyouvKw",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "No mapping found for [creationDate] in order to sort on",
          "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
          "index" : "kitodo"
        }
      }
    ]
  },
  "status" : 400
}

	at org.kitodo.data.elasticsearch.search.SearchRestClient.getDocument(SearchRestClient.java:188) ~[kitodo-data-management-3.0.0-alpha.2.jar:?]
	at org.kitodo.data.elasticsearch.search.Searcher.findDocuments(Searcher.java:218) ~[kitodo-data-management-3.0.0-alpha.2.jar:?]
	at org.kitodo.services.data.base.SearchService.findByQuery(SearchService.java:525) ~[classes/:3.0.0-alpha.2]
	at de.sub.goobi.forms.BatchForm.filterProcesses(BatchForm.java:129) [classes/:3.0.0-alpha.2]
	at de.sub.goobi.forms.BatchForm.filterAll(BatchForm.java:226) [classes/:3.0.0-alpha.2]
	at de.sub.goobi.forms.BatchForm.initializeBatchList(BatchForm.java:236) [classes/:3.0.0-alpha.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:97) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:80) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.util.bean.IsolatedForwardingBean.create(IsolatedForwardingBean.java:45) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:76) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:758) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62) [el-api.jar:3.0.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.el.VariableResolverImpl.resolveVariable(VariableResolverImpl.java:65) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.custom.redirectTracker.RedirectTrackerVariableResolver.resolveVariable(RedirectTrackerVariableResolver.java:41) [tomahawk-sandbox20-1.1.10-SNAPSHOT.jar:1.1.10-SNAPSHOT]
	at org.apache.myfaces.custom.security.SecurityContextVariableResolver.resolveVariable(SecurityContextVariableResolver.java:45) [tomahawk-sandbox20-1.1.10-SNAPSHOT.jar:1.1.10-SNAPSHOT]
	at org.apache.myfaces.el.convert.VariableResolverToELResolver.getValue(VariableResolverToELResolver.java:132) [myfaces-impl-2.2.12.jar:2.2.12]
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62) [el-api.jar:3.0.FR]
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94) [jasper-el.jar:8.5.34]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:137) [jasper-el.jar:8.5.34]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190) [jasper-el.jar:8.5.34]
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50) [weld-servlet-2.4.3.Final.jar:2.4.3.Final]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96) [myfaces-impl-2.2.12.jar:2.2.12]
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:360) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIInput.getValue(UIInput.java:159) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:324) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.renderValue(HtmlTextRendererBase.java:278) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.renderInputBegin(HtmlTextRendererBase.java:200) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.renderInput(HtmlTextRendererBase.java:180) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.encodeEnd(HtmlTextRendererBase.java:69) [myfaces-impl-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.RendererUtils.renderChildren(RendererUtils.java:688) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.shared.renderkit.html.HtmlGroupRendererBase.encodeEnd(HtmlGroupRendererBase.java:150) [myfaces-impl-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551) [myfaces-api-2.2.12.jar:2.2.12]
	at org.primefaces.component.tabview.TabViewRenderer.encodeTabContent(TabViewRenderer.java:313) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.tabview.TabViewRenderer.encodeContents(TabViewRenderer.java:271) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.tabview.TabViewRenderer.encodeMarkup(TabViewRenderer.java:132) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.tabview.TabViewRenderer.encodeEnd(TabViewRenderer.java:71) [primefaces-6.1.jar:6.1]
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675) [myfaces-api-2.2.12.jar:2.2.12]
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89) [primefaces-6.1.jar:6.1]
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123) [primefaces-6.1.jar:6.1]
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58) [primefaces-6.1.jar:6.1]
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313) [myfaces-impl-2.2.12.jar:2.2.12]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58) [myfaces-api-2.2.12.jar:2.2.12]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.tomahawk.application.ResourceViewHandlerWrapper.renderView(ResourceViewHandlerWrapper.java:169) [tomahawk21-1.1.14.jar:1.1.14]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.tomahawk.application.ResourceViewHandlerWrapper.renderView(ResourceViewHandlerWrapper.java:169) [tomahawk21-1.1.14.jar:1.1.14]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58) [myfaces-api-2.2.12.jar:2.2.12]
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121) [omnifaces-2.6.3.jar:2.6.3]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267) [myfaces-impl-2.2.12.jar:2.2.12]
	at org.apache.myfaces.custom.ppr.PPRLifecycleWrapper.render(PPRLifecycleWrapper.java:84) [tomahawk-sandbox20-1.1.10-SNAPSHOT.jar:1.1.10-SNAPSHOT]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200) [myfaces-api-2.2.12.jar:2.2.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at de.sub.goobi.helper.servletfilter.HibernateSessionFilter2.doFilter(HibernateSessionFilter2.java:53) [classes/:3.0.0-alpha.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at de.sub.goobi.helper.servletfilter.RequestControlFilter.doFilter(RequestControlFilter.java:159) [classes/:3.0.0-alpha.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at de.sub.goobi.helper.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:67) [classes/:3.0.0-alpha.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:357) [tomahawk21-1.1.14.jar:1.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.kitodo.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:65) [classes/:3.0.0-alpha.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.6.2.jar:2.6.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.34]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-coyote.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.elasticsearch.client.ResponseException: GET http://elasticsearch:9200/kitodo/process/_search?pretty=true&from=0&size=500: HTTP/1.1 400 Bad Request
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "No mapping found for [creationDate] in order to sort on",
        "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
        "index" : "kitodo"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "kitodo",
        "node" : "JTrmz0_SRU2cNG-iyouvKw",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "No mapping found for [creationDate] in order to sort on",
          "index_uuid" : "dnBjzSWBS76VxWuJYjvvMQ",
          "index" : "kitodo"
        }
      }
    ]
  },
  "status" : 400
}

	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354) ~[elasticsearch-rest-client-5.6.5.jar:5.6.5]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343) ~[elasticsearch-rest-client-5.6.5.jar:5.6.5]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
	... 1 more
```

interestingly, the elasticsearch instance logged the following before requesting the mentioned url:

```
[2018-10-02T15:47:07,341][INFO ][o.e.c.m.MetaDataMappingService] [JTrmz0_] [kitodo/dnBjzSWBS76VxWuJYjvvMQ] create_mapping [client]
[2018-10-02T15:48:52,030][INFO ][o.e.c.m.MetaDataMappingService] [JTrmz0_] [kitodo/dnBjzSWBS76VxWuJYjvvMQ] create_mapping [project]
```

these are the only log entries that point to a mapping creation though kitodo had been running a while at that point.

**Comment by henning-gerhardt** [comment]
Documentation was wrong for creating elastic search index by curl command `curl -s -X PUT "http://elasticsearch:9200/kitodo`. Elastic search index should only created by application through indexing page. See PR #1834 and changed wiki page https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung-f%C3%BCr-Kitodo.Production-3.x
