### ISSUE TITLE
2.x: Thumbnail creation fails in metadata editor if TIFF contains big metadata fields

### ISSUE THREAD

**Issue by ponchofiesta** [kitodo/kitodo-production#2785]
We have a problem in the metadata editor in Kitodo.Production 2.2. Some of our TIFF master images have very big metadata fields filled by the scanner software ("Cruse"). When K.Prod tries to read them, it fails with this error:

```
ERROR 2019-06-25 14:53:50,707 (TiffInterpreter.java:read:148)                                                                                                                                                                                
        something went wrong during reading of image                                                                                                                                                                                         
java.lang.ClassCastException: [J cannot be cast to com.sun.media.imageioimpl.plugins.tiff.TIFFIFD                                                                                                                                            
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getIFDAsTree(TIFFImageMetadata.java:175)                                                                                                                                 
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getNativeTree(TIFFImageMetadata.java:205)                                                                                                                                
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getAsTree(TIFFImageMetadata.java:193)
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.getImageMetadata(TIFFImageReader.java:831)
        at de.unigoettingen.sub.commons.contentlib.imagelib.TiffInterpreter.read(TiffInterpreter.java:141)
        at de.unigoettingen.sub.commons.contentlib.imagelib.TiffInterpreter.<init>(TiffInterpreter.java:99)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageFileFormat.getInterpreter(ImageFileFormat.java:134)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageFileFormat.getInterpreter(ImageFileFormat.java:117)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.init(ImageManager.java:126)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.<init>(ImageManager.java:99)
        at de.sub.goobi.metadaten.MetadatenImagesHelper.scaleFile(MetadatenImagesHelper.java:357)
        at de.sub.goobi.metadaten.Metadaten.BildErmitteln(Metadaten.java:1697)
        at de.sub.goobi.metadaten.Metadaten.BildBlaettern(Metadaten.java:1484)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.myfaces.el.MethodBindingImpl.invoke(MethodBindingImpl.java:132)
        at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:61)
        at javax.faces.component.UICommand.broadcast(UICommand.java:109)
        at org.ajax4jsf.component.AjaxActionComponent.broadcast(AjaxActionComponent.java:62)
        at org.ajax4jsf.component.AjaxViewRoot.processEvents(AjaxViewRoot.java:184)
        at org.ajax4jsf.component.AjaxViewRoot.broadcastEvents(AjaxViewRoot.java:162)
        at org.ajax4jsf.component.AjaxViewRoot.processDecodes(AjaxViewRoot.java:278)
        at org.apache.myfaces.lifecycle.ApplyRequestValuesExecutor.execute(ApplyRequestValuesExecutor.java:32)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:95)
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:70)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:139)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.ajax4jsf.webapp.BaseXMLFilter.doXmlFilter(BaseXMLFilter.java:141)
        at org.ajax4jsf.webapp.BaseFilter.doFilter(BaseFilter.java:281)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.SessionCounterFilter.doFilter(SessionCounterFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.HibernateSessionFilter2.doFilter(HibernateSessionFilter2.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.SecurityCheckFilter.doFilter(SecurityCheckFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.RequestControlFilter.doFilter(RequestControlFilter.java:147)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:341)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
ERROR 2019-06-25 14:53:50,710 (ImageManager.java:init:129)
        Error while getting ImageInterpreter
ERROR 2019-06-25 14:53:50,711 (Metadaten.java:BildErmitteln:1701)
        de.unigoettingen.sub.commons.contentlib.exceptions.ImageManagerException: de.unigoettingen.sub.commons.contentlib.exceptions.ImageInterpreterException: Something went wrong while reading the TIFF from input stream
ERROR 2019-06-25 14:53:50,711 (Metadaten.java:BildErmitteln:1701)
        de.unigoettingen.sub.commons.contentlib.exceptions.ImageManagerException: de.unigoettingen.sub.commons.contentlib.exceptions.ImageInterpreterException: Something went wrong while reading the TIFF from input stream
```

If I remove the big metadata fields using `exiftool -XMP-Cruse:all= image.tif` the thumbnail can be created without problems.

Exiftool and Imagemagick (`identify -verbose`) can read the metadata without problems. Thus I think it is a bug in K.Prod respectively the used ImageIO library.

Here is a sample TIFF file containing this metadata:
https://tubcloud.tu-berlin.de/s/YEYiH3iMMcRiCNk

**Comment by ponchofiesta** [comment]
Same problem in Kitodo.Production 2.3:

```
ERROR 2019-08-08 10:47:14,472 de.unigoettingen.sub.commons.contentlib.imagelib.TiffInterpreter.read(TiffInterpreter.java:148)
        something went wrong during reading of image
java.lang.ClassCastException: [J cannot be cast to com.sun.media.imageioimpl.plugins.tiff.TIFFIFD
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getIFDAsTree(TIFFImageMetadata.java:175)
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getNativeTree(TIFFImageMetadata.java:205)
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageMetadata.getAsTree(TIFFImageMetadata.java:193)
        at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.getImageMetadata(TIFFImageReader.java:831)
        at de.unigoettingen.sub.commons.contentlib.imagelib.TiffInterpreter.read(TiffInterpreter.java:141)
        at de.unigoettingen.sub.commons.contentlib.imagelib.TiffInterpreter.<init>(TiffInterpreter.java:99)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageFileFormat.getInterpreter(ImageFileFormat.java:134)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageFileFormat.getInterpreter(ImageFileFormat.java:117)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.init(ImageManager.java:126)
        at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.<init>(ImageManager.java:99)
        at de.sub.goobi.metadaten.MetadatenImagesHelper.scaleFile(MetadatenImagesHelper.java:357)
        at de.sub.goobi.metadaten.Metadaten.BildErmitteln(Metadaten.java:1697)
        at de.sub.goobi.metadaten.Metadaten.BildGeheZu(Metadaten.java:1509)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.myfaces.el.MethodBindingImpl.invoke(MethodBindingImpl.java:132)
        at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:61)
        at javax.faces.component.UICommand.broadcast(UICommand.java:109)
        at org.ajax4jsf.component.AjaxActionComponent.broadcast(AjaxActionComponent.java:62)
        at org.ajax4jsf.component.AjaxViewRoot.processEvents(AjaxViewRoot.java:184)
        at org.ajax4jsf.component.AjaxViewRoot.broadcastEvents(AjaxViewRoot.java:162)
        at org.ajax4jsf.component.AjaxViewRoot.processApplication(AjaxViewRoot.java:350)
        at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:32)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:95)
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:70)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:139)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.ajax4jsf.webapp.BaseXMLFilter.doXmlFilter(BaseXMLFilter.java:141)
        at org.ajax4jsf.webapp.BaseFilter.doFilter(BaseFilter.java:281)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.SessionCounterFilter.doFilter(SessionCounterFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.HibernateSessionFilter2.doFilter(HibernateSessionFilter2.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.SecurityCheckFilter.doFilter(SecurityCheckFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at de.sub.goobi.helper.servletfilter.RequestControlFilter.doFilter(RequestControlFilter.java:147)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.myfaces.webapp.filter.ExtensionsFilter.doFilter(ExtensionsFilter.java:341)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
ERROR 2019-08-08 10:47:14,483 de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.init(ImageManager.java:129)
        Error while getting ImageInterpreter
ERROR 2019-08-08 10:47:14,485 de.sub.goobi.metadaten.Metadaten.BildErmitteln(Metadaten.java:1701)
        de.unigoettingen.sub.commons.contentlib.exceptions.ImageManagerException: de.unigoettingen.sub.commons.contentlib.exceptions.ImageInterpreterException: Something went wrong while reading the TIFF from input stream
ERROR 2019-08-08 10:47:14,485 de.sub.goobi.metadaten.Metadaten.BildErmitteln(Metadaten.java:1701)
        de.unigoettingen.sub.commons.contentlib.exceptions.ImageManagerException: de.unigoettingen.sub.commons.contentlib.exceptions.ImageInterpreterException: Something went wrong while reading the TIFF from input stream
```

**Comment by henning-gerhardt** [comment]
Kitodo.Production 2.x is using a very strict implementation of the TIFF Reader through [Kitodo.ContentServer library](https://github.com/kitodo/kitodo-contentserver). This strict implementation report us (SLUB Dresden) in the past some invalid TIFF images which was "good" enough for displaying or processing through other tools.

A colleague of me and I checked your provided TIFF file through a few tools (checkit_tiff, DPF-Manager)  and and this file contain a few errors regarding the base TIFF format like:
- tiff tags like Artist (315) and ImgeDescription (270) contains non 7bit ASCII characters
- tiff tag ExifIFDOffset need a long value instead of an IFD value
- tiff tag Compression (259) contains value for LZW compression which is not allowed for RGB images or has the wrong compression value

If I re-read your posted stack trace then I think the error come from the wrong value for the ExifIFDOffset. Maybe your scanner software must be adjusted to produce correct tiff tags - especially for this tag.

It should be discussed if Kitodo.Production should be strict or error tolerating like other programs (exiftools, imagemagick, ...) but I would prefer the strict rules / behaviour with an improved error message.

**Comment by ponchofiesta** [comment]
Thank you for investigating. I can confirm that working images (from same process) without this exception do not have this error in DPF-Manager. I will get in touch with the vendor.

Personally I prefer robust software with error tolerance and not too strict handling. As K.Prod 3.0 is ready soon, I would not invest too much time here. That's because I've done the quick and dirty fix in the pull requests. We are happy with it.

**Comment by M3ssman** [comment]
Are there news regarding this Issue? 

ULB Sachsen-Anhalt hangs in a similar way, too. We receive TIFFs from very different Scanners, some of them integrate binary data into the TIFF-Tags.

**Comment by henning-gerhardt** [comment]
So far as I know there is no development planed to change the behaviour for images in Kitodo.Production 2.x or the Kitodo.ContentServer library. As long the TIFF image files are correct according to [checkit_tiff](http://art1pirat.spdns.org/art1/checkit_tiff) or [DPF Manager](http://dpfmanager.org/) the files should be displayed in Kitodo.Production 2.x.

**Comment by solth** [comment]
Closed as no further development for Kitodo.Production 2.x is planned (see https://github.com/kitodo/kitodo-production/security/policy)
