### ISSUE TITLE
3.0: Duplication of project folders

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3187]
A project folder may get duplicated in the project edit page:

![Screenshot_2020-02-13 Kitodo Production](https://user-images.githubusercontent.com/1378632/74444448-2eb55f80-4e75-11ea-9865-412a8155241d.png)

Create a new project, go to the folders section and create a folder and confirm. Open the folder dialog and confirm again. Now the folder gets displayed twice. 
After that,
- the mouse cursor stays in wait mode.
-  if you emmediately click on "Save", Kitodo doesn't redirect (the project, however is created but I don't know if only partially?).
- it won't show the folder edit dialog and you won't be able to delete the folder.

An exception is logged:

```
 java.lang.IllegalStateException: Duplicate key images, DEFAULT
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        ...
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.kitodo.production.forms.ProjectForm.getFolderMap(ProjectForm.java:490)
        at org.kitodo.production.forms.ProjectForm.setPreview(ProjectForm.java:592)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

If you reload the page (F5, not Ctrl-F5) , you can go on configuring the project. Esp. you can delete the duplicate folder entry and save the project.

**Comment by matthias-ronge** [comment]
**Objective:** The system should refuse to add an existing folder once again.

**Comment by matthias-ronge** [comment]
The reason is a wrong implementation of `hashCode()` and `equals()` in the `Folder` bean, which [require special semantics](https://stackoverflow.com/a/2720173) in Hibernate.
