### ISSUE TITLE
Elasticsearch initialization fails

### ISSUE THREAD

**Issue by ponchofiesta** [kitodo/kitodo-production#3210]
When clicking "ElasticSearch Mapping erzeugen" I get a hugh pagefilling red error that hides in milliseconds. The _kitodo.log_ file says:
<details>
  <summary>Click to expand</summary>
<code>
[ERROR] 2020-02-18 10:12:00.091 [http-nio-8080-exec-9] IndexingForm - PUT http://localhost:9200/kitodo: HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [filter : {dynamic=strict, properties={user={type=long}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [template : {dynamic=strict, properties={projects={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, workflow={properties={title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, ruleset={type=long}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, active={type=boolean}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [process : {dynamic=strict, properties={template={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, parent={properties={id={type=long}}}, sortHelperImages={type=long}, comments={properties={id={type=long}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, hasChildren={type=boolean}, sortHelperMetadata={type=long}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, templates={properties={id={type=long}}}, ruleset={type=long}, project={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, processBaseUri={type=text, fields={keyword={ignore_above=256, type=keyword}}}, workpieces={properties={id={type=long}}}, batches={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, wikiField={type=text, fields={keyword={ignore_above=256, type=keyword}}}, meta={dynamic=false, properties={ID={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mdWrap={properties={MDTYPE={type=text, fields={keyword={ignore_above=256, type=keyword}}}, xmlData={properties={kitodo={properties={kitodo={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metadata={type=nested, properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, content={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}}}}}}}, sortHelperArticles={type=long}, sortHelperDocstructs={type=long}, properties={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [task : {dynamic=strict, properties={homeDirectory={type=text, fields={keyword={ignore_above=256, type=keyword}}}, clientForTask={type=long}, typeAutomatic={type=boolean}, ordering={type=long}, roles={properties={id={type=long}}}, typeMetadata={type=boolean}, projectForTask={type=long}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, batchStep={type=boolean}, processingTime={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingBegin={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingUser={properties={surname={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, processingStatus={type=long}, typeImagesWrite={type=boolean}, processingEnd={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, typeImagesRead={type=boolean}, templateForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, editType={type=long}, processForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, correction={type=boolean}}}] [workflow : {dynamic=strict, properties={client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, status={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [batch : {dynamic=strict, properties={processes={properties={template={type=boolean}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [property : {dynamic=strict, properties={workpieces={properties={id={type=long}}}, processes={properties={id={type=long}}}, templates={properties={id={type=long}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [ruleset : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, orderMetadataByRuleset={type=boolean}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [project : {dynamic=strict, properties={fileFormatDmsExport={type=text, fields={keyword={ignore_above=256, type=keyword}}}, processes={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, endDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, numberOfVolumes={type=long}, templates={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, active={type=boolean}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, users={properties={surname={type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, folder={properties={path={type=text, fields={keyword={ignore_above=256, type=keyword}}}, urlStructure={type=text, fields={keyword={ignore_above=256, type=keyword}}}, fileGroup={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mimeType={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, numberOfPages={type=long}, fileFormatInternal={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metsRightsOwner={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, startDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}}}] [docket : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [filter : {dynamic=strict, properties={user={type=long}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [template : {dynamic=strict, properties={projects={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, workflow={properties={title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, ruleset={type=long}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, active={type=boolean}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [process : {dynamic=strict, properties={template={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, parent={properties={id={type=long}}}, sortHelperImages={type=long}, comments={properties={id={type=long}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, hasChildren={type=boolean}, sortHelperMetadata={type=long}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, templates={properties={id={type=long}}}, ruleset={type=long}, project={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, processBaseUri={type=text, fields={keyword={ignore_above=256, type=keyword}}}, workpieces={properties={id={type=long}}}, batches={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, wikiField={type=text, fields={keyword={ignore_above=256, type=keyword}}}, meta={dynamic=false, properties={ID={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mdWrap={properties={MDTYPE={type=text, fields={keyword={ignore_above=256, type=keyword}}}, xmlData={properties={kitodo={properties={kitodo={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metadata={type=nested, properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, content={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}}}}}}}, sortHelperArticles={type=long}, sortHelperDocstructs={type=long}, properties={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [task : {dynamic=strict, properties={homeDirectory={type=text, fields={keyword={ignore_above=256, type=keyword}}}, clientForTask={type=long}, typeAutomatic={type=boolean}, ordering={type=long}, roles={properties={id={type=long}}}, typeMetadata={type=boolean}, projectForTask={type=long}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, batchStep={type=boolean}, processingTime={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingBegin={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingUser={properties={surname={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, processingStatus={type=long}, typeImagesWrite={type=boolean}, processingEnd={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, typeImagesRead={type=boolean}, templateForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, editType={type=long}, processForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, correction={type=boolean}}}] [workflow : {dynamic=strict, properties={client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, status={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [batch : {dynamic=strict, properties={processes={properties={template={type=boolean}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [property : {dynamic=strict, properties={workpieces={properties={id={type=long}}}, processes={properties={id={type=long}}}, templates={properties={id={type=long}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [ruleset : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, orderMetadataByRuleset={type=boolean}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [project : {dynamic=strict, properties={fileFormatDmsExport={type=text, fields={keyword={ignore_above=256, type=keyword}}}, processes={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, endDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, numberOfVolumes={type=long}, templates={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, active={type=boolean}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, users={properties={surname={type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, folder={properties={path={type=text, fields={keyword={ignore_above=256, type=keyword}}}, urlStructure={type=text, fields={keyword={ignore_above=256, type=keyword}}}, fileGroup={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mimeType={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, numberOfPages={type=long}, fileFormatInternal={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metsRightsOwner={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, startDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}}}] [docket : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [filter : {dynamic=strict, properties={user={type=long}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [template : {dynamic=strict, properties={projects={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, workflow={properties={title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, ruleset={type=long}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, active={type=boolean}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [process : {dynamic=strict, properties={template={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, parent={properties={id={type=long}}}, sortHelperImages={type=long}, comments={properties={id={type=long}, message={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, hasChildren={type=boolean}, sortHelperMetadata={type=long}, sortHelperStatus={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, templates={properties={id={type=long}}}, ruleset={type=long}, project={properties={active={type=boolean}, client={properties={id={type=long}}}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, docket={type=long}, processBaseUri={type=text, fields={keyword={ignore_above=256, type=keyword}}}, workpieces={properties={id={type=long}}}, batches={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, wikiField={type=text, fields={keyword={ignore_above=256, type=keyword}}}, meta={dynamic=false, properties={ID={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mdWrap={properties={MDTYPE={type=text, fields={keyword={ignore_above=256, type=keyword}}}, xmlData={properties={kitodo={properties={kitodo={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metadata={type=nested, properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, content={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}}}}}}}, sortHelperArticles={type=long}, sortHelperDocstructs={type=long}, properties={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, tasks={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}}}] [task : {dynamic=strict, properties={homeDirectory={type=text, fields={keyword={ignore_above=256, type=keyword}}}, clientForTask={type=long}, typeAutomatic={type=boolean}, ordering={type=long}, roles={properties={id={type=long}}}, typeMetadata={type=boolean}, projectForTask={type=long}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, batchStep={type=boolean}, processingTime={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingBegin={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, processingUser={properties={surname={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, processingStatus={type=long}, typeImagesWrite={type=boolean}, processingEnd={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, typeImagesRead={type=boolean}, templateForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, editType={type=long}, processForTask={properties={id={type=long}, title={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, correction={type=boolean}}}] [workflow : {dynamic=strict, properties={client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, status={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [batch : {dynamic=strict, properties={processes={properties={template={type=boolean}, id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}] [property : {dynamic=strict, properties={workpieces={properties={id={type=long}}}, processes={properties={id={type=long}}}, templates={properties={id={type=long}}}, creationDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, type={type=text, fields={keyword={ignore_above=256, type=keyword}}}, value={type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [ruleset : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, orderMetadataByRuleset={type=boolean}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}] [project : {dynamic=strict, properties={fileFormatDmsExport={type=text, fields={keyword={ignore_above=256, type=keyword}}}, processes={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, endDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}, numberOfVolumes={type=long}, templates={properties={id={type=long}, title={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, active={type=boolean}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}, users={properties={surname={type=text, fields={keyword={ignore_above=256, type=keyword}}}, name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}, login={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, folder={properties={path={type=text, fields={keyword={ignore_above=256, type=keyword}}}, urlStructure={type=text, fields={keyword={ignore_above=256, type=keyword}}}, fileGroup={type=text, fields={keyword={ignore_above=256, type=keyword}}}, mimeType={type=text, fields={keyword={ignore_above=256, type=keyword}}}}}, numberOfPages={type=long}, fileFormatInternal={type=text, fields={keyword={ignore_above=256, type=keyword}}}, metsRightsOwner={fielddata=true, type=text, fields={keyword={ignore_above=256, type=keyword}}}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, startDate={format=yyyy-MM-dd HH:mm:ss, ignore_malformed=true, type=date}}}] [docket : {dynamic=strict, properties={file={type=text, fields={keyword={ignore_above=256, type=keyword}}}, active={type=boolean}, client={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}, title={fielddata=true, type=text, fields={raw={index=false, type=text}, keyword={ignore_above=256, type=keyword}}}}}]"}},"status":400}
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354) ~[elasticsearch-rest-client-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343) ~[elasticsearch-rest-client-5.6.5.jar:5.6.5]
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) ~[httpcore-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

</code>
</details>

Elasticsearch authentication is disabled.

- Kitodo.Production 3.0.0
- Elasticsearch 7.6.0

**Comment by ponchofiesta** [comment]
Sorry, Elasticsearch 7.6 is unsupported. Didn't read docs correctly.
