### ISSUE TITLE
NPE when creating an Issue

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#3229]
Sometimes (not yet determined when exactly) a NPE occurs, when creating an Issue

```
 java.lang.NullPointerException
	at org.kitodo.production.model.bibliography.course.IndividualIssue.getBreakMark(IndividualIssue.java:116)
	at org.kitodo.production.model.bibliography.course.Course.splitInto(Course.java:771)
	at org.kitodo.production.forms.CalendarForm.setGranularity(CalendarForm.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.setValue(BeanELResolver.java:122)
```

It also occurs when clicking the granularity buttons on the second tab. (Same Stack Trace)

**Comment by Kathrin-Huber** [comment]
The problem seems to be an empty granularity default selection. When navigating to the second tab the first time, there is no granularity selected. In further steps this leads to a NPE.
![granularity](https://user-images.githubusercontent.com/22615787/75251881-c7d06880-57db-11ea-9b8e-053139a5df74.PNG)

**Comment by solth** [comment]
I can't reproduce the error. When navigating to the granularity tab for the first time, the "Issues" granularity is correctly preselected, which corresponds to https://github.com/kitodo/kitodo-production/blob/21515d33a81ba59aa418713f42862b714189f8d4/Kitodo/src/main/java/org/kitodo/production/forms/CalendarForm.java#L91

<img width="1429" alt="Bildschirmfoto 2020-02-25 um 16 21 32" src="https://user-images.githubusercontent.com/19183925/75261167-ebe77600-57ea-11ea-843e-77a1de548552.png">

**Comment by Kathrin-Huber** [comment]
I could also not reproduce it
