### ISSUE TITLE
Properties cannot be indexed

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3508]
When starting indexing "over everything" for properties…

![Screenshot](https://user-images.githubusercontent.com/3040657/79994141-dffbf580-84b5-11ea-8094-c6f813342d9e.jpg)

…there is the following error message:
```
Apr 22, 2020 4:20:46 PM org.omnifaces.exceptionhandler.FullAjaxExceptionHandler logException
SCHWERWIEGEND: FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/pages/error.jsf' will be shown.
ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:323)
	at org.kitodo.data.elasticsearch.search.SearchRestClient.getDocument(SearchRestClient.java:185)
	at org.kitodo.data.elasticsearch.search.Searcher.findDocuments(Searcher.java:204)
	at org.kitodo.production.services.data.base.SearchService.findAllDocuments(SearchService.java:402)
	at org.kitodo.production.services.data.base.SearchService.findAllIDs(SearchService.java:163)
	at org.kitodo.production.services.index.IndexingService.startIndexing(IndexingService.java:264)
	at org.kitodo.production.forms.IndexingForm.callIndexing(IndexingForm.java:144)
	...
	Suppressed: org.elasticsearch.client.ResponseException: POST http://localhost:9200/kitodo/property/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512: HTTP/1.1 500 Internal Server Error
{"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [15000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"kitodo","node":"kpiKtOOOQgqZBrHS7uIB5g","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [15000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
		... 1 more
```

This is how the error is displayed in the user interface:

![Screenshot of indexing error](https://user-images.githubusercontent.com/3040657/79994091-d1add980-84b5-11ea-8626-3566769cdd37.jpg)

On the contrary, when the entire index is created, properties are indexed without hesitation.

**Goal:** Indexing should work.

**Comment by Kathrin-Huber** [comment]
This is fixed by #3366
