### ISSUE TITLE
Indexing issue:  corrupt mets file: mimetype value

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#3695]
After migrating existing meta data files to new format with the provided transformation file and start indexing all the data this error appear in the `catalina.out` file:

```
Exception in thread "Indexing 320000 of type PROCESS" java.lang.IllegalArgumentException: Corrupt file: <mets:fileGrp USE="LOCAL"> contains differing MIMETYPE values: , image/tiff
        at org.kitodo.dataformat.access.UseXmlAttributeAccess.<init>(UseXmlAttributeAccess.java:67)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.kitodo.dataformat.access.MetsXmlElementAccess.<init>(MetsXmlElementAccess.java:123)
        at org.kitodo.dataformat.access.MetsXmlElementAccess.read(MetsXmlElementAccess.java:194)
        at org.kitodo.production.services.dataformat.MetsService.loadWorkpiece(MetsService.java:105)
        at org.kitodo.production.services.dataformat.MetsService.getBaseType(MetsService.java:84)
        at org.kitodo.production.services.data.ProcessService.getBaseType(ProcessService.java:1702)
        at org.kitodo.production.services.data.ProcessService.addAllObjectsToIndex(ProcessService.java:246)
        at org.kitodo.production.helper.IndexWorker.indexObjects(IndexWorker.java:116)
        at org.kitodo.production.helper.IndexWorker.indexChunks(IndexWorker.java:110)
        at org.kitodo.production.helper.IndexWorker.run(IndexWorker.java:78)
        at java.lang.Thread.run(Thread.java:748)
```

As I did not get any information about which meta data file of which process is causing this error I can not add an excerpt of a meta data file.

I don't know how this error is influencing the index operation.

**Comment by henning-gerhardt** [comment]
With you change in #3968 is was possible for me to get a "corrupt" meta data file. The reason for the output is, that this process contains `mets:file` entries with a "filled" `MIMETYPE` attribute from older 2.x versions and an empty `MIMETYPE` attribute from current 2.x versions.

```xml
...
      <mets:file ID="FILE_0523" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:///home/goobi/work/daten/5046/images/scans_tif/00000523.tif"/>
      </mets:file>
      <mets:file ID="FILE_0524" MIMETYPE="">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:///home/goobi/work/daten/5046/images/scans_tif/00000524.tif"/>
      </mets:file>
...
```

I don't know why current 2.x versions did not add the MIMETYPE information anymore or not in any case.
