### ISSUE TITLE
Workflow cannot be saved

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3758]
When trying to saving a workflow, it gets the following error. This was happening with the workflow from the migration test VM which did not get all the arrows (after correcting them manually):

Date/time: 2020-06-10 13:47:03  
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0  
User IP: 192.168.91.1  
Request URI: /kitodo/pages/workflowEdit.jsf  
Ajax request: Yes  
Status code: 500  
Exception type: class org.camunda.bpm.model.xml.ModelParseException  
Exception message: SAXException while parsing input stream  
Exception UUID:  
Stack trace:

```
    org.camunda.bpm.model.xml.ModelParseException: SAXException while parsing input stream
    	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:245)
    	at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.parseModelFromStream(AbstractModelParser.java:98)
    	at org.camunda.bpm.model.bpmn.impl.BpmnParser.parseModelFromStream(BpmnParser.java:65)
    	at org.camunda.bpm.model.bpmn.Bpmn.doReadModelFromInputStream(Bpmn.java:249)
    	at org.camunda.bpm.model.bpmn.Bpmn.readModelFromStream(Bpmn.java:131)
    	at org.kitodo.production.workflow.model.Reader.loadProcess(Reader.java:118)
    	at org.kitodo.production.workflow.model.Reader.<init>(Reader.java:67)
    	at org.kitodo.production.workflow.model.Converter.<init>(Converter.java:63)
    	at org.kitodo.production.forms.WorkflowForm.hasMultipleSructureTreeConfiguration(WorkflowForm.java:175)
    	at org.kitodo.production.forms.WorkflowForm.saveAndRedirect(WorkflowForm.java:146)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
    	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
    	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
    	at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
    	at org.springframework.faces.webflow.FlowActionListener.processAction(FlowActionListener.java:71)
    	at org.springframework.faces.model.SelectionTrackingActionListener.processAction(SelectionTrackingActionListener.java:64)
    	at javax.faces.component.UICommand.broadcast(UICommand.java:120)
    	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
    	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
    	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
    	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
    	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
    	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:69)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
    	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:56)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
    	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: org.xml.sax.SAXException: Error: URI=null Line=42: cvc-complex-type.4: Attribut 'sourceRef' muss in Element 'bpmn2:sequenceFlow' vorkommen.
    	at org.camunda.bpm.model.xml.impl.util.DomUtil$DomErrorHandler.error(DomUtil.java:202)
    	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:137)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.addDefaultAttributes(XMLSchemaValidator.java:2937)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2055)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:761)
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
    	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
    	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:240)
    	... 90 more
```

Database to reproduce this: [dump.sql](https://gist.github.com/matthias-ronge/0149beb6410bf8bc23cab42164d970b1)

Steps to reproduce: Go to system » migrate. Click “Create workflow”, select all projects, proceed, select first line from database (with 5 processes). In the window that appears, choose “create new workflow”. Do required changes to workflow (add missing arrows, assign roles to steps), click “save”.

**Comment by Erikmitk** [comment]
> Attribut 'sourceRef' muss in Element 'bpmn2:sequenceFlow' vorkommen.

The underlying xml representation seems to be corrupted. If the workflow xml was wrong and missing the connections somehow it might be that manually correcting them put the workflow in a weird state? That might get solved by looking at the xml in #3754.

**Comment by matthias-ronge** [comment]
<details>
<summary>XML after saving</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:template="http://www.kitodo.org/template" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="ChangeME" name="ChangeME" isExecutable="false" template:outputName="ChangeME">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:outgoing>SequenceFlow_1</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:task id="Task_1" name="Titelaufnahme" template:editType="4" template:processingStatus="1" template:permittedUserRole="1" template:typeMetadata="false" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="false" template:typeImagesWrite="false" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_1</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_2</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_1" sourceRef="StartEvent_1" targetRef="Task_1" />
    <bpmn2:task id="Task_2" name="Scannen" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="false" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="true" template:typeImagesWrite="true" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_2</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_3</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_2" sourceRef="Task_1" targetRef="Task_2" />
    <bpmn2:task id="Task_3" name="TIFs einspielen" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="true" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="true" template:typeImagesWrite="true" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_3</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_4</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_3" sourceRef="Task_2" targetRef="Task_3" />
    <bpmn2:task id="Task_4" name="Seitenkontrolle und-paginierung" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="true" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="true" template:typeImagesWrite="true" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_4</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_5</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_4" sourceRef="Task_3" targetRef="Task_4" />
    <bpmn2:task id="Task_5" name="Struktur- und Metadatenerfassung" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="true" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="true" template:typeImagesWrite="true" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_5</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_6</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_5" sourceRef="Task_4" targetRef="Task_5" />
    <bpmn2:task id="Task_6" name="Export Digitale Bibliothek" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="true" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="true" template:typeImagesWrite="true" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_6</bpmn2:incoming>
      <bpmn2:outgoing>Flow_078asc0</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_6" sourceRef="Task_5" targetRef="Task_6" />
    <bpmn2:task id="Task_8" name="PubPharm Datensatz" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="false" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="false" template:typeImagesWrite="false" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_8</bpmn2:incoming>
      <bpmn2:incoming>Flow_078asc0</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_9</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_8" targetRef="Task_8" />
    <bpmn2:task id="Task_9" name="Titelaufnahme O-Datensatz" template:editType="4" template:processingStatus="0" template:permittedUserRole="1" template:typeMetadata="false" template:separateStructure="false" template:typeAutomatic="false" template:typeImagesRead="false" template:typeImagesWrite="false" template:typeExportDMS="false" template:typeAcceptClose="false" template:typeCloseVerify="false" template:batchStep="false" template:concurrent="true" template:repeatOnCorrection="false">
      <bpmn2:incoming>SequenceFlow_9</bpmn2:incoming>
      <bpmn2:outgoing>Flow_0zz0irg</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:sequenceFlow id="SequenceFlow_9" sourceRef="Task_8" targetRef="Task_9" />
    <bpmn2:endEvent id="EndEvent_1">
      <bpmn2:incoming>SequenceFlow_9</bpmn2:incoming>
      <bpmn2:incoming>Flow_0zz0irg</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_078asc0" sourceRef="Task_6" targetRef="Task_8" />
    <bpmn2:sequenceFlow id="Flow_0zz0irg" sourceRef="Task_9" targetRef="EndEvent_1" />
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="ChangeME">
      <bpmndi:BPMNEdge id="SequenceFlow_9_di" bpmnElement="SequenceFlow_9">
        <di:waypoint x="1498" y="258" />
        <di:waypoint x="1548" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1523" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_6_di" bpmnElement="SequenceFlow_6">
        <di:waypoint x="1198" y="258" />
        <di:waypoint x="1248" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1223" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_5_di" bpmnElement="SequenceFlow_5">
        <di:waypoint x="1048" y="258" />
        <di:waypoint x="1098" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1073" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_4_di" bpmnElement="SequenceFlow_4">
        <di:waypoint x="898" y="258" />
        <di:waypoint x="948" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="923" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_3_di" bpmnElement="SequenceFlow_3">
        <di:waypoint x="748" y="258" />
        <di:waypoint x="798" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="773" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_2_di" bpmnElement="SequenceFlow_2">
        <di:waypoint x="598" y="258" />
        <di:waypoint x="648" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="623" y="247" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="SequenceFlow_1_di" bpmnElement="SequenceFlow_1">
        <di:waypoint x="448" y="258" />
        <di:waypoint x="498" y="258" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="473" y="237" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_078asc0_di" bpmnElement="Flow_078asc0">
        <di:waypoint x="1348" y="258" />
        <di:waypoint x="1398" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0zz0irg_di" bpmnElement="Flow_0zz0irg">
        <di:waypoint x="1648" y="258" />
        <di:waypoint x="1698" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_1" bpmnElement="StartEvent_1">
        <dc:Bounds x="412" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_1_di" bpmnElement="Task_1">
        <dc:Bounds x="498" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_2_di" bpmnElement="Task_2">
        <dc:Bounds x="648" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_3_di" bpmnElement="Task_3">
        <dc:Bounds x="798" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_4_di" bpmnElement="Task_4">
        <dc:Bounds x="948" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_5_di" bpmnElement="Task_5">
        <dc:Bounds x="1098" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_6_di" bpmnElement="Task_6">
        <dc:Bounds x="1248" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_8_di" bpmnElement="Task_8">
        <dc:Bounds x="1398" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_9_di" bpmnElement="Task_9">
        <dc:Bounds x="1548" y="218" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="EndEvent_1_di" bpmnElement="EndEvent_1">
        <dc:Bounds x="1698" y="240" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1716" y="280" width="0" height="12" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>
```
</details>

**Comment by matthias-ronge** [comment]
It looks like this is a follow-up error because of #3754 and #3761 happening. Therefore, I flag this as duplicate.
