### ISSUE TITLE
Production template is created from wrong workflow file ChangeMe.bpnm20.xml

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3761]
In migration, you have created a workflow. You assigned a role to each step and save successfully. No error message shows. Then you assign processes to production template. This seems to work, but in the log file, the error message is recorded:

```
[ERROR] 2020-06-10 14:17:32.633 [http-nio-8080-exec-1] MigrationForm - errorSaving
org.kitodo.exceptions.WorkflowException: Der Workflowaufgabe 'Begutachtung Bestandserhaltung' wurden keine Rollen zugewiesen.
	at org.kitodo.production.workflow.model.Converter.getTask(Converter.java:139) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.workflow.model.Converter.validateWorkflowTaskList(Converter.java:93) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.workflow.model.Converter.convertWorkflowToTemplate(Converter.java:70) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.forms.MigrationForm.createNewTemplate(MigrationForm.java:406) [classes/:3.2.0-SNAPSHOT]
	...
```

It appears that the state in which the Workflow Editor started is used to create the production template. When saving, the status is either not saved or it is not updated internally.

Database to reproduce this: [dump.sql](https://gist.github.com/matthias-ronge/0149beb6410bf8bc23cab42164d970b1)

Steps to reproduce: Go to system » migrate. Click “Create workflow”, select all projects, proceed, select second line from database (with 4 processes). In the window that appears, choose “create new workflow”. Do required changes to workflow (assign roles), click “save”. Create production template.

The production template has no steps. If you try to run hierarchy migration, creation of superior processes fails in validation step.

**Comment by matthias-ronge** [comment]
The problem is related to #3757: Because of missing update, workflow is saved to its new name (what you typed in, like “default”), but then it is re-read from ChangeMe.xml (which exists at that point) and the latter does not contain roles assigned.
