### ISSUE TITLE
ElasticSearch "TooManyClauses" error with medium sized database

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#3763]
When using the system after freshly indexing a medium sized database (~53k entries to be indexed), a `ViewExpiredException` is thrown when trying to load the pages `desktop`, `processes` and `projects`:
![Bildschirmfoto 2020-06-11 um 13 45 09](https://user-images.githubusercontent.com/19183925/84381778-cc355b80-abe9-11ea-8e77-332016885858.png)

Apparently, the system builds a query with the IDs of all 45k tasks at one point, the ElasticSearch log shows a `BooleanQuery$TooManyClauses: maxClauseCount is set to 1024` error with the following stack trace:
```
[2020-06-11T11:20:11,969][DEBUG][o.e.a.s.TransportSearchAction] [luoIW-P] [kitodo][3], node[luoIW-PQS9-GqNQ6wfugKw], [P], s[STARTED], a[id=p8jXjmrWR2uTzmTB-Oxy3Q]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[kitodo], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[task], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=5, batchedReduceSize=512, preFilterShardSize=128, source={
  "size" : 10000,
  "query" : {
    "bool" : {
      "must" : [
        {
          "bool" : {
            "must" : [
              {
                "terms" : {
                  "_id" : [
                    801,
                    802,
                    803,
                    806,
                    809,
                    815,
                    816,
                    817,
                    820,
...
```

the list contains the ids of _all_ ~45k tasks in the database, than:

```
...
                 48104
                ],
                "boost" : 1.0
              }
            },
            {
              "bool" : {
                "must" : [
                  {
                    "bool" : {
                      "must" : [
                        {
                          "terms" : {
                            "projectForTask" : [
                              1
                            ],
                            "boost" : 1.0
                          }
                        },
                        {
                          "match" : {
                            "clientForTask" : {
                              "query" : 1,
                              "operator" : "OR",
                              "prefix_length" : 0,
                              "max_expansions" : 50,
                              "fuzzy_transpositions" : true,
                              "lenient" : false,
                              "zero_terms_query" : "NONE",
                              "boost" : 1.0
                            }
                          }
                        }
                      ],
                      "disable_coord" : false,
                      "adjust_pure_negative" : true,
                      "boost" : 1.0
                    }
                  },
                  {
                    "match" : {
                      "clientForTask" : {
                        "query" : 1,
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "boost" : 1.0
                      }
                    }
                  }
                ],
                "disable_coord" : false,
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            }
          ],
          "disable_coord" : false,
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      {
        "match" : {
          "clientForTask" : {
            "query" : 1,
            "operator" : "OR",
            "prefix_length" : 0,
            "max_expansions" : 50,
            "fuzzy_transpositions" : true,
            "lenient" : false,
            "zero_terms_query" : "NONE",
            "boost" : 1.0
          }
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:312) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:617) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.5.jar:5.6.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:125) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.BooleanQuery$Builder.add(BooleanQuery.java:138) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.elasticsearch.index.query.TermsQueryBuilder.handleTermsQuery(TermsQueryBuilder.java:453) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.TermsQueryBuilder.doToQuery(TermsQueryBuilder.java:414) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:444) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:418) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:444) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:418) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.5.jar:5.6.5]
	... 14 more
```

**Temporary workaround:** Setting `indices.query.bool.max_clause_count` to `50000` in `elasticsearch.yml` prevents the error, but doesn't seem like a workable solution for really large databases.

**Comment by Kathrin-Huber** [comment]
It turned out to be a specific problem with the underlying database.
