### ISSUE TITLE
Metadata editor crashes after a few clicks

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3884]
- Move the mouse over a page

![Bildschirmfoto_0005](https://user-images.githubusercontent.com/3040657/89021930-8d866c80-d321-11ea-82f1-630c6161fa17.png)

- Right click to open the mouse menu

![Bildschirmfoto_0006](https://user-images.githubusercontent.com/3040657/89021961-98410180-d321-11ea-9e30-4a5d08bfc4fd.png)

- Click the only option. The dialog appears.

![Bildschirmfoto_0007](https://user-images.githubusercontent.com/3040657/89022004-a4c55a00-d321-11ea-9954-10edf7daab55.png)

- Click "Cancel".
- Move the mouse over a page

![Bildschirmfoto_0008](https://user-images.githubusercontent.com/3040657/89022054-b3ac0c80-d321-11ea-8716-c84f8379877b.png)

- Right click to open the mouse menu. The menu is still very shortly visible ...

![Bildschirmfoto_0009](https://user-images.githubusercontent.com/3040657/89022070-b9a1ed80-d321-11ea-9015-3d5b5823b2db.png)

- ... then the editor crashes.

![Bildschirmfoto_0010](https://user-images.githubusercontent.com/3040657/89022177-e3f3ab00-d321-11ea-8265-6b18067b0af0.png)

Stacktrace:
```
java.lang.IllegalStateException
    at org.kitodo.production.forms.dataeditor.AddDocStrucTypeDialog.getStructuralElementView(AddDocStrucTypeDialog.java:598)
    at org.kitodo.production.forms.dataeditor.AddDocStrucTypeDialog.prepareSelectAddableMetadataTypesItems(AddDocStrucTypeDialog.java:518)
    at org.kitodo.production.forms.dataeditor.MetadataPanel.showPageInLogical(MetadataPanel.java:145)
    at org.kitodo.production.forms.dataeditor.GalleryPanel.selectMedia(GalleryPanel.java:735)
    at org.kitodo.production.forms.dataeditor.GalleryPanel.select(GalleryPanel.java:775)
```

**Comment by solth** [comment]
@matthias-ronge could you test whether the problems still persists after https://github.com/kitodo/kitodo-production/pull/3927 has been merged?

**Comment by matthias-ronge** [comment]
The problem can still be reproduced with current master at 8b5e52770c01c821035a82dfd02a6a5f05bc9e31.
