### ISSUE TITLE
Export - XSLT processing - "EmptyTask - Could not create XSLT transformer"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4065]
Version used: 3.2.1-build 07.10.2020

I get in error if I use something like this
`      <xsl:if test="$contentIDs or $purlURL">`
in xsl during Export.
If I comment out (or delete) the lines 
58: `<xsl:if test="$contentIDs or $purlURL">`
and 75: `</xsl:if>`
in this file
[ruleset_CCS_v6-formatted.txt](https://github.com/kitodo/kitodo-production/files/5445332/ruleset_CCS_v6-formatted.txt)
the error does not occure anymore.
I also have checked this XSL against schema-for-xslt20.xsd using this tool [https://www.freeformatter.com/xml-validator-xsd.html](url) --> result: XSL is ok.
==> so, maybe there is something in the software?

Full Exception text:
[ERROR] 2020-10-27 13:34:53.921 [Export process: 202010261625News] EmptyTask - Could not create XSLT transformer. Check /usr/local/kitodo/xslt/ruleset_CCS_v6..xsl for errors.
java.lang.IllegalArgumentException: Could not create XSLT transformer. Check /usr/local/kitodo/xslt/ruleset_CCS_v6..xsl for errors.
        at org.kitodo.export.XsltHelper.transformXmlByXslt(XsltHelper.java:54) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportMets.writeMetsFile(ExportMets.java:161) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportDms.asyncExportWithImport(ExportDms.java:295) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportDms.exportImagesAndMetsToDestinationUri(ExportDms.java:239) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportDms.prepareExportLocation(ExportDms.java:219) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportDms.startExport(ExportDms.java:191) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.export.ExportDms.startExport(ExportDms.java:143) ~[classes/:3.2.1-SNAPSHOT]
        at org.kitodo.production.helper.tasks.ExportDmsTask.run(ExportDmsTask.java:65) [classes/:3.2.1-SNAPSHOT]

**Comment by stefanCCS** [comment]
Ok, found it by myself ...
If you install saxonb-xslt, you can run the XSLT process in Linux command line like this:
`saxonb-xslt -s:/usr/local/kitodo/metadata/144/meta.xml -xsl:ruleset_CCS_v6..xsl -o:myoutput.xml`
--> In my case this has resulted to: 
`Variable $purlURL has not been declared`
--> So, I could find my typo in my xsl file
