### ISSUE TITLE
OPAC import broken

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4192]
Trying to create a new process from a template ("+" button next to a project) results in the following error:
```
SCHWERWIEGEND: Servlet.service() for servlet [Faces Servlet] in context with path [/kitodo] threw exception ["Falscher Typ: 'org.kitodo.production.dto.ProcessDTO' muss 'process' sein!"] with root cause
javax.faces.convert.ConverterException: "Falscher Typ: 'org.kitodo.production.dto.ProcessDTO' muss 'process' sein!"
	at org.kitodo.production.converter.BeanConverter.getAsString(BeanConverter.java:77)
	at org.kitodo.production.converter.ProcessConverter.getAsString(ProcessConverter.java:31)
	at org.primefaces.renderkit.SelectRenderer.getOptionAsString(SelectRenderer.java:191)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeOption(SelectOneMenuRenderer.java:547)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeSelectItems(SelectOneMenuRenderer.java:531)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeHiddenSelect(SelectOneMenuRenderer.java:208)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeInput(SelectOneMenuRenderer.java:177)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeMarkup(SelectOneMenuRenderer.java:139)
	at org.primefaces.component.selectonemenu.SelectOneMenuRenderer.encodeEnd(SelectOneMenuRenderer.java:107)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:87)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:69)
	at org.primefaces.component.row.RowRenderer.encodeEnd(RowRenderer.java:64)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
...
```

Probably caused by #4166

**Comment by matthias-ronge** [comment]
The reason for this is #3540
