### ISSUE TITLE
Unnecessary saving of workflow BPNM file when creating process template

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4219]
For some reason, Production wants to save the workflow BPNM diagram when you’re adding a process template. This is unnecessary overhead and leads to errors in case the file is not present.

![Screenshot](https://user-images.githubusercontent.com/3040657/109293270-d8228580-782b-11eb-95de-43792dbb2670.png)

Stack trace:
```
[ERROR] 2021-02-26 11:07:24.711 [http-nio-8080-exec-2] TemplateForm - errorDiagram
java.io.FileNotFoundException: D:\Daten\Production_3\diagrams\Example_Workflow.bpmn20.xml (Das System kann den angegebenen Pfad nicht finden)
	at java.net.URL.openStream(URL.java:1068) ~[?:1.8.0_282]
	at org.kitodo.filemanagement.FileManagement.read(FileManagement.java:87) ~[kitodo-file-management-3.2.1-SNAPSHOT.jar:?]
	at org.kitodo.production.services.file.FileService.read(FileService.java:323) ~[classes/:3.2.1-SNAPSHOT]
	at org.kitodo.production.workflow.model.Reader.<init>(Reader.java:54) ~[classes/:3.2.1-SNAPSHOT]
	at org.kitodo.production.workflow.model.Converter.<init>(Converter.java:50) ~[classes/:3.2.1-SNAPSHOT]
	at org.kitodo.production.forms.TemplateForm.prepareTasks(TemplateForm.java:400) ~[classes/:3.2.1-SNAPSHOT]
	at org.kitodo.production.forms.TemplateForm.save(TemplateForm.java:130) [classes/:3.2.1-SNAPSHOT]
```

**Goal:** Do not save workflow file when adding process template.

**Comment by solth** [comment]
The stacktrace suggest that the system does not try to _save_ the BPNM workflow file, but rather just _read_ it (which makes sense, since the template tasks are created from the individual workflow steps).

So I guess the problem lies rather in the wrong error message being displayed ("Fehler beim Speichern..." instead of "Fehler beim Öffnen...") than actually trying to save the workflow xml file.

**Comment by matthias-ronge** [comment]
> The stacktrace suggest that the system does not try to _save_ the BPNM workflow file, but rather just _read_ it (which makes sense, since the template tasks are created from the individual workflow steps).
> 
> So I guess the problem lies rather in the wrong error message being displayed ("Fehler beim Speichern..." instead of "Fehler beim Öffnen...") than actually trying to save the workflow xml file.

I just thought the same
