### ISSUE TITLE
Current master doesn’t start on Tomcat

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4708]
When I try to start the current build, I am getting the following error:

```
SCHWERWIEGEND: Servlet.service() for servlet [Faces Servlet] in context with path [/kitodo] threw exception ['void org.elasticsearch.client.RestHighLevelClient.<init>(org.elasticsearch.client.RestClientBuilder)'] with root cause
java.lang.NoSuchMethodError: 'void org.elasticsearch.client.RestHighLevelClient.<init>(org.elasticsearch.client.RestClientBuilder)'
	at org.kitodo.data.elasticsearch.KitodoRestClient.initiateClient(KitodoRestClient.java:94)
	at org.kitodo.data.elasticsearch.KitodoRestClient.initiateClient(KitodoRestClient.java:68)
	at org.kitodo.data.elasticsearch.index.IndexRestClient.getInstance(IndexRestClient.java:63)
	at org.kitodo.production.services.index.IndexingService.<clinit>(IndexingService.java:83)
	at org.kitodo.production.services.ServiceManager.initializeIndexingService(ServiceManager.java:320)
	at org.kitodo.production.services.ServiceManager.getIndexingService(ServiceManager.java:716)
	at org.kitodo.production.forms.IndexingForm.getServerInformation(IndexingForm.java:241)
```

When I check the class in Eclipse, it doesn’t show any errors:

![No error in Eclipse](https://user-images.githubusercontent.com/3040657/135232614-9c13ba8c-9857-4aff-91f5-226b6959b031.png)

It looks like there is a dependency missing at runtime.

Tested using Tomcat 9.0.43 run on JDK 11.0.10_9 (launched from within Eclipse).

**Comment by solth** [comment]
Since the ElasticSearch client was updated to version 7.10 in #4581 you need to replace your current ElasticSearch _server_ with a new instance with version 7.10, too.

**Comment by joerg-liebenow** [comment]
We hat the same problem and the solution was to delete old elasticsearch jar-files from application-server (/WEB-INF/lib//elasticsearch***5.6.16.jar)

**Comment by matthias-ronge** [comment]
I did update to ElasticSearch 7, but the problem is independent of it. NoSuchMethodError means that Java will not find any bytecode for that method in the bytecode of RestHighLevelClient.class

Yes, I don't have any elasticsearch-5*.jar on my classpath either.

**Comment by matthias-ronge** [comment]
Ultimately, I cannot say what led to the error. I created a new Eclipse workspace today and re-cloned, built and imported the master, and now everything works. I close the issue as not reproducible.
