### ISSUE TITLE
NumberFormatException on search for task title

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4918]
If you open a extended search for processes which should contain a specific task title in a specific state then a `NumberFormatException` is sometimes thrown. For example if you search for all processes which have an "open" task called "Erfassen der Meta- und Strukturdaten" then the following exception is thrown:

```
 [DEBUG] 2022-01-20 17:10:01,267 [http-nio-127.0.0.1-8080-exec-14] org.kitodo.production.services.data.FilterService - For input string: "Erfassen der Meta"
java.lang.NumberFormatException: For input string: "Erfassen der Meta"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at org.kitodo.production.services.data.FilterService.getTaskStart(FilterService.java:963) ~[classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.services.data.FilterService.filterTaskRange(FilterService.java:704) ~[classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.services.data.FilterService.createTaskFilters(FilterService.java:606) [classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.services.data.FilterService.queryBuilder(FilterService.java:181) [classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.helper.SearchResultGeneration.getQueryForFilter(SearchResultGeneration.java:91) [classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.services.data.ProcessService.getQueryForFilter(ProcessService.java:369) [classes/:3.4.1-SNAPSHOT]
        at org.kitodo.production.forms.ProcessForm.getAmount(ProcessForm.java:1160) [classes/:3.4.1-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:88) [tomcat9-el-api.jar:?]
        at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62) [tomcat9-el-api.jar:?]
....
```

Its looks for me that the "-" character is interpreted as a negative sign followed by a number which is not the case.

The "good" thing is, that the search is starting and is showing the processes but this exception should not happen.

**Comment by matthias-ronge** [comment]
The behavior is intentional. If you enter two numbers here, a task range (from-to) will be processed. The exception is only caught and logged in debug mode, this is also intentional as we have specified in the Coding Guidelines that _every_ caught exception is to be logged.

This is not a bug. However, we could change log level to `TRACE` for intentionally caught exceptions, see #4499
