### ISSUE TITLE
Uploading images does not work

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5034]
When I want to use the function to upload an image: When I select a JPG image, the dialog complains that the file format is invalid. When I upload a TIF image, the application spends some time working. A green confirmation bar also appears that the image was successfully processed. But, no new image appears.

![Screencast](https://user-images.githubusercontent.com/3040657/158346415-2b06cb38-3c11-4cfa-a1b6-c913145d6dbd.gif)

I checked the process folder. No new files arrive there.

I get the following report in the log: 

```
März 15, 2022 10:19:42 AM org.primefaces.util.FileUploadUtils isValidType
WARNING: The type of the uploaded file kitodo.tif could not be validated
javax.script.ScriptException: java.lang.NullPointerException: JavaScript ScriptEngine not available via the context ClassLoader or the extension ClassLoader.
	at org.primefaces.util.FileUploadUtils.isValidFileName(FileUploadUtils.java:176)
	at org.primefaces.util.FileUploadUtils.isValidType(FileUploadUtils.java:143)
	at org.primefaces.util.FileUploadUtils.isValidFile(FileUploadUtils.java:297)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:101)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:53)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:59)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:479)
	at javax.faces.component.UIInput.decode(UIInput.java:371)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1408)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:207)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:775)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1019)
	[...]
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: JavaScript ScriptEngine not available via the context ClassLoader or the extension ClassLoader.
	... 101 more

[TRACE] 2022-03-15 10:19:45.721 [http-nio-8080-exec-8] FileService - Searching for media took 2 ms
```

I put a break point in the first line of `UploadFileDialog.uploadMedia()` but it wasn’t reached.

**Comment by solth** [comment]
Could this be related to (and in fact get fixed by) #4913 ?

**Comment by matthias-ronge** [comment]
Unfortunately no, I just tested it, but no change at all.

**Comment by matthias-ronge** [comment]
```
//We use rhino or nashorn javascript engine bundled with java to re-evaluate javascript regex that cannot be
  easily translated to java regex
//TODO If at some day nashorn will not be bundled with java (http://openjdk.java.net/jeps/335), we have to put
  some notes in the user guide
```

Found here:

![source](https://user-images.githubusercontent.com/3040657/158380534-98edbfd0-32c5-4d71-a1f7-acecb9ce6e6b.png)

Apparently there will be missing classes in newer Java versions. Maybe it can be resubmitted via the POM file?

_On my development machine, the Tomcat runs with Java 15 (as part of Eclipse bundle). I must check the customer server which Java version they use._

**Comment by matthias-ronge** [comment]
Related: https://github.com/primefaces/primefaces/issues/6461

**Comment by solth** [comment]
Perhaps you could update the issue title and description with you findings?
