### ISSUE TITLE
Unclear error message after deletion of a process 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5120]
### Problem
After a process is deleted, an error message occurs: 
- `Fehler beim Hochladen von Home.`

It is not clear, why this message appears and what should be done, but it can be stated that: 
1. the process is **not available** anymore in the process list
2. the process is **not available** anymore in the index
3. ~~the folder with the meta.xml, ... is **still available** in the file system~~ 
Update 2022-05-03: This is due to the local configuration in the SLUB and must be regarded. 

### Solution 
When the error message is necessary, it should be clearly described, why it appears and what needs to be done by the user. 
When the error message is not necessary, it should not appear. 

### Example
![FehlerLöschenVorgang](https://user-images.githubusercontent.com/14835770/166243980-9a8ee5ed-b971-4f92-8c1d-a88de70cd870.jpg)

**Comment by matthias-ronge** [comment]
Corresponding stack trace:
```
WebDav - errorUploading
java.io.IOException: No user for home directory!
        at org.kitodo.production.services.data.UserService.getHomeDirectory(UserService.java:363)
        at org.kitodo.production.helper.WebDav.uploadFromHome(WebDav.java:131)
        at org.kitodo.production.services.data.ProcessService.deleteSymlinksFromUserHomes(ProcessService.java:2424)
        at org.kitodo.production.services.data.ProcessService.deleteMetadataDirectory(ProcessService.java:2400)
        at org.kitodo.production.services.data.ProcessService.deleteProcess(ProcessService.java:2375)
        at org.kitodo.production.forms.ProcessListBaseView.delete(ProcessListBaseView.java:478)
        at …
```

It looks like the code here is trying to do more than it should. The features of the `WebDav` class are obscure. I think that's that thing with the `fertig/` folder. It's not clear how this feature was ever conceived. We don't support it and this code should be removed.

Related: #3448

**Comment by matthias-ronge** [comment]
By the way, I also see an error deleting the directory. It is not because it shouldn’t happen on our system (but maybe a local problem, i.e. permissions thing). Just because you mentioned it, I leave the stack trace, too:
```
ProcessService - errorDirectoryDeleting
org.apache.commons.io.IOExceptionList: /usr/local/kitodo/metadata/7500
    at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:331)
    at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1192)
    at org.kitodo.filemanagement.FileManagement.delete(FileManagement.java:139)
    at org.kitodo.production.services.file.FileService.delete(FileService.java:455)
    at org.kitodo.production.services.data.ProcessService.deleteMetadataDirectory(ProcessService.java:2404)
    at org.kitodo.production.services.data.ProcessService.deleteProcess(ProcessService.java:2375)
    at org.kitodo.production.forms.ProcessListBaseView.delete(ProcessListBaseView.java:478)
```

**Comment by matthias-ronge** [comment]
See also #3258 #3448
