### ISSUE TITLE
Unhandled NPE in LazyProcessDTOModel class method load

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5709]
The following null pointer exception get logged in catalina.out:

```
java.lang.NullPointerException
    at org.kitodo.production.model.LazyProcessDTOModel.load(LazyProcessDTOModel.java:107)
    at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:567)
    at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:130)
    at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:93)
    at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
    at javax.faces.component.UIData.encodeEnd(UIData.java:1835)
    at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
    at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
    at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
    at org.primefaces.component.api.UIData.visitTree(UIData.java:913)
    at javax.faces.component.UIForm.visitTree(UIForm.java:357)
....
```

**Version** 3.6.0-SNAPSHOT

**Comment by henning-gerhardt** [comment]
One possible source of this issue may the search for a PPN of a process title.
