### ISSUE TITLE
Unhandled NPE in User class class constructor

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5711]
The following null pointer exception get logged in catalina.out:

```
Caused by: java.lang.NullPointerException
    at org.kitodo.data.database.beans.User.<init>(User.java:131)
    at org.kitodo.production.services.data.UserService.getCurrentUser(UserService.java:215)
    at org.kitodo.production.controller.SessionClientController.getAvailableClientsOfCurrentUser(SessionClientController.java:148)
    at org.kitodo.production.controller.SessionClientController.userHasOnlyOneClient(SessionClientController.java:61)
    at org.kitodo.production.controller.SessionClientController.getCurrentSessionClientName(SessionClientController.java:47)
    at jdk.internal.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566
....
```

**Version** 3.6.0-SNAPSHOT

**Comment by matthias-ronge** [comment]
Some context: If a user session has expired, Tomcat wants to show the error page. But the error page cannot be shown because it references `/WEB-INF/templates/base.xhtml`, which relies on a user being present, and fails if there is not.

```
29-Feb-2024 15:44:34.039 SEVERE [http-nio-8080-exec-10] org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.logException [ca301d7e-754d-4ce2-a967-76c0d96a15d6][0:0:0:0:0:0:0:1] FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/pages/error.jsf' will be shown.
	java.lang.IllegalStateException: getAttribute: Session already invalidated
		at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1148)
		at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:102)
		at org.jboss.weld.context.beanstore.http.AbstractSessionBeanStore.getAttribute(AbstractSessionBeanStore.java:100)
		at org.jboss.weld.context.beanstore.AttributeBeanStore.get(AttributeBeanStore.java:138)
		at org.jboss.weld.context.beanstore.http.AbstractSessionBeanStore.get(AbstractSessionBeanStore.java:85)
		at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:83)
		at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:114)
		at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:70)
		at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:95)
		at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
		at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
		at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:785)
		at org.jboss.weld.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
		at org.jboss.weld.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
		at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49)
		at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
		at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
		at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:93)
		at org.apache.el.parser.AstValue.getTarget(AstValue.java:69)
		at org.apache.el.parser.AstValue.getType(AstValue.java:57)
		at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:173)
		at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
		at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
		at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getType(ContextAwareTagValueExpression.java:76)
		at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:160)
		at org.primefaces.renderkit.InputRenderer.getConvertedValue(InputRenderer.java:45)
		at javax.faces.component.UIInput.getConvertedValue(UIInput.java:789)
		at javax.faces.component.UIInput.validate(UIInput.java:708)
		at javax.faces.component.UIInput.processValidators(UIInput.java:293)
		at javax.faces.component.UIForm.processValidators(UIForm.java:210)
		at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
		at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
		at javax.faces.component.UIViewRoot._processValidatorsDefault(UIViewRoot.java:1782)
		at javax.faces.component.UIViewRoot.access$600(UIViewRoot.java:81)
		at javax.faces.component.UIViewRoot$ProcessValidatorPhaseProcessor.process(UIViewRoot.java:1889)
		at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
		at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:982)
		at org.apache.myfaces.lifecycle.ProcessValidationsExecutor.execute(ProcessValidationsExecutor.java:38)
		at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
		at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
		at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
		at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147)
		at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
		at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
29-Feb-2024 15:44:34.053 SEVERE [http-nio-8080-exec-10] org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.logException [ca301d7e-754d-4ce2-a967-76c0d96a15d6][0:0:0:0:0:0:0:1] FullAjaxExceptionHandler: Well, another exception occurred during rendering error page '/pages/error.jsf'. Trying to render a hardcoded error page now.
	javax.el.ELException: Error reading [currentSessionClientName] on type [org.kitodo.production.controller.SessionClientController]
		at javax.el.BeanELResolver.getValue(BeanELResolver.java:101)
		at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
		at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
		at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
		at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
		at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
		at org.apache.myfaces.view.facelets.el.ELText$ELTextVariable.writeText(ELText.java:218)
		at org.apache.myfaces.view.facelets.compiler.TextInstruction.write(TextInstruction.java:45)
		at org.apache.myfaces.view.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:46)
		at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:80)
		at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:70)
		at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:86)
		at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:70)
		at org.primefaces.component.overlaypanel.OverlayPanelRenderer.encodeMarkup(OverlayPanelRenderer.java:73)
		at org.primefaces.component.overlaypanel.OverlayPanelRenderer.encodeEnd(OverlayPanelRenderer.java:51)
		at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
		at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
		at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
		at org.apache.myfaces.context.servlet.PartialViewContextImpl.processRenderAll(PartialViewContextImpl.java:697)
		at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:490)
		at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:420)
		at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
		at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
		at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
		at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:571)
		at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:542)
		at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
		at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.renderErrorPageView(FullAjaxExceptionHandler.java:566)
		at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handleAjaxException(FullAjaxExceptionHandler.java:434)
		at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handle(FullAjaxExceptionHandler.java:383)
		at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:216)
		at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
		at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
		at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
		at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147)
		at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
		at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.lang.NullPointerException
		at org.kitodo.data.database.beans.User.<init>(User.java:131)
		at org.kitodo.production.services.data.UserService.getCurrentUser(UserService.java:215)
		at org.kitodo.production.controller.SessionClientController.getAvailableClientsOfCurrentUser(SessionClientController.java:148)
		at org.kitodo.production.controller.SessionClientController.userHasOnlyOneClient(SessionClientController.java:61)
		at org.kitodo.production.controller.SessionClientController.getCurrentSessionClientName(SessionClientController.java:47)
		at jdk.internal.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
		... 111 more
```
