### ISSUE TITLE
Deleting new process results in IOException

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5775]
**Describe the bug**
A new process was created but in a wrong way. Deleting this process results in an error message visible for the user "No user for home directory!" (missing translation!) and a logged IOException.

```
[ERROR] 2023-09-07 14:01:06,950 [http-nio-127.0.0.1-8080-exec-3] org.kitodo.production.helper.WebDav - errorUploading
java.io.IOException: No user for home directory!
        at org.kitodo.production.services.data.UserService.getHomeDirectory(UserService.java:353) ~[classes/:3.6.0-SNAPSHOT]
        at org.kitodo.production.helper.WebDav.uploadFromHome(WebDav.java:131) ~[classes/:3.6.0-SNAPSHOT]
        at org.kitodo.production.services.data.ProcessService.deleteSymlinksFromUserHomes(ProcessService.java:2354) ~[classes/:3.6.0-SNAPSHOT]
        at org.kitodo.production.services.data.ProcessService.deleteMetadataDirectory(ProcessService.java:2330) ~[classes/:3.6.0-SNAPSHOT]
        at org.kitodo.production.services.data.ProcessService.deleteProcess(ProcessService.java:2305) ~[classes/:3.6.0-SNAPSHOT]
        at org.kitodo.production.forms.ProcessListBaseView.delete(ProcessListBaseView.java:554) ~[classes/:3.6.0-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) ~[tomcat9-jasper-el-9.0.43.jar:9.0.43]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) ~[tomcat9-jasper-el-9.0.43.jar:9.0.43]
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-servlet-2.4.8.Final.jar:2.4.8.Final]
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-servlet-2.4.8.Final.jar:2.4.8.Final]
        at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96) ~[myfaces-impl-2.3.10.jar:2.3.10]
        at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74) ~[myfaces-impl-2.3.10.jar:2.3.10]
        at org.springframework.faces.webflow.FlowActionListener.processAction(FlowActionListener.java:71) ~[spring-faces-2.5.1.RELEASE.jar:2.5.1.RELEASE]
        at org.springframework.faces.model.SelectionTrackingActionListener.processAction(SelectionTrackingActionListener.java:64) ~[spring-faces-2.5.1.RELEASE.jar:2.5.1.RELEASE]
        at javax.faces.component.UICommand.broadcast(UICommand.java:120) ~[myfaces-api-2.3.10.jar:2.3.10]
        at javax.faces.component.UIData.broadcast(UIData.java:1732) ~[myfaces-api-2.3.10.jar:2.3.10]
...
```

So far as I can see the process data inside the database and in the file system is deleted. I did not figure out if related data is even deleted in the elastic search indices.

The responding code looks a little bit wrong for me (https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java#L340C1-L356C6):

```java
    public URI getHomeDirectory(User user) throws IOException {
        URI homeDirectory;
        if (Objects.nonNull(user)) {
            if (ConfigCore.getBooleanParameterOrDefaultValue(ParameterCore.LDAP_USE)) {
                homeDirectory = Paths.get(ServiceManager.getLdapServerService().getUserHomeDirectory(user)).toUri();
            } else {
                homeDirectory = Paths.get(ConfigCore.getParameter(ParameterCore.DIR_USERS), user.getLogin()).toUri();
            }

            if (!new File(homeDirectory).exists()) {
                ServiceManager.getFileService().createDirectoryForUser(homeDirectory, user.getLogin());
            }
        } else {
            throw new IOException("No user for home directory!");
        }
        return homeDirectory;
    }
```

If user object is null then throwing an IOException?

**Expected behavior**
Deleting a new process should not end in a thrown exception and if so the message should be translated into the user language.

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Comment by BartChris** [comment]
Was this maybe fixed with https://github.com/kitodo/kitodo-production/pull/5614?

**Comment by henning-gerhardt** [comment]
Thanks for hinting to this possible solution. I will look into this solution.
