### ISSUE TITLE
Error message on not matching regular expression on referenced files

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5793]
**Describe the bug**
In 2.x there was no check if the given files in the media directory was really correct or not. You could put JPEG or TIFF files into it and this files was referenced inside the meta.xml file of the process.

In 3.x there is a more restrictive check that the files in the media directory are correct and in 3.x there is even a check that the references files match the pattern of the given folder information. F.e. you define in a directory scans_tif that there should only be TIFF files (*.tif) then this will be checked against the files on the file system and in the reference in the meta.xml file.

But if there are mismatches like define *.tif files in the scans_tif directory but there is only a *.jpg files in the meta.xml file referenced, the user get a default error message window as the thrown exception is not fetched in a correct way.

The error message window looks like

```

Es ist ein Fehler aufgetreten:

    Date/time: 2023-09-28 08:35:21
    User agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
    User IP: 127.0.0.1
    Request URI: /kitodo/pages/metadataEditor.jsf
    Ajax request: No
    Status code: 500
    Exception type: class java.lang.IllegalStateException
    Exception message: Regular expression "(.*)\.\Qtif\E" didn't match on "file:///home/goobi/work/daten/151046/images/scans_tif/00000001.jpg"
    Exception UUID:
    Stack trace:

    java.lang.IllegalStateException: Regular expression "(.*)\.\Qtif\E" didn't match on "file:///home/goobi/work/daten/151046/images/scans_tif/00000001.jpg"
    	at org.kitodo.production.model.Subfolder.lambda$createKeyMapperForPattern$0(Subfolder.java:109)
    	at org.kitodo.production.model.Subfolder.getCanonical(Subfolder.java:192)
    	at org.kitodo.production.services.file.FileService.getCanonicalFileNamePartsAndSanitizeAbsoluteURIs(FileService.java:1178)
    	at org.kitodo.production.services.file.FileService.searchForMedia(FileService.java:1107)
    	at org.kitodo.production.forms.dataeditor.DataEditorForm.openMetsFile(DataEditorForm.java:333)
    	at org.kitodo.production.forms.dataeditor.DataEditorForm.open(DataEditorForm.java:268)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
    	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
...
```

Even the used regular expression was more confusing then helpful as the folder information is not defined in such way.

**Expected behavior**
If a regular expression did not match on checking the file references then a well written error message should be appear.

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Workaround**
Replacing the .jpg references files with .tif file ending.

**Comment by solth** [comment]
@henning-gerhardt Does this still occur for you in current versions of the software?

**Comment by henning-gerhardt** [comment]
@solth:  I try to reproduce this issue. This did not happen many times but I opened this issue to get not lost. So I must construct this again.

**Comment by henning-gerhardt** [comment]
@solth: I can still reproduce this issue.

**Comment by solth** [comment]
@henning-gerhardt Thanks for verifying that it still occurs!

**Comment by henning-gerhardt** [comment]
@solth: maybe your solution #7196 can fix this issue too. Should I try your solution #7196 for issue #7195 too?

**Comment by solth** [comment]
> [@solth](https://github.com/solth): maybe your solution [#7196](https://github.com/kitodo/kitodo-production/pull/7196) can fix this issue too. Should I try your solution [#7196](https://github.com/kitodo/kitodo-production/pull/7196) for issue [#7195](https://github.com/kitodo/kitodo-production/issues/7195) too?

@henning-gerhardt You mean you will check if #7196 fixes this issue (5793) as well? If so, yes, thank you, please check that, if you don't mind!

**Comment by henning-gerhardt** [comment]
@solth: your fix in #7196 did work for my error usage scenario. Instead of showing a stack trace it shows now the main error message:

<img width="1003" height="208" alt="Image" src="https://github.com/user-attachments/assets/d79c5ba1-5570-4b84-8ff7-d2f0a5072fbf" />

With this is should now be possible to report back such kind of errors from the user to an administrator to fix it in the background as a user did not have any chance to fix itself.

**Comment by solth** [comment]
@henning-gerhardt thank you for verifying this. I will link this issue to be fixed by #7196 as well, then, alright?

**Comment by henning-gerhardt** [comment]
Yes, you can add this issue to the pull request so it will be closed on merging the pull request.
