### ISSUE TITLE
Resetting process state results in Java out of memory error

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5813]
**Describe the bug**
Resetting a lot of processes over a lot of process tasks is resulting in Java Out Of Memory Errors.

Output in Tomcat9 catalina.out
```
[2023-10-19 09:50:59] [info] Exception in thread "I/O dispatcher 1" java.lang.OutOfMemoryError: Java heap space
[2023-10-19 09:50:59] [info] Exception in thread "C3P0PooledConnectionPoolManager[identityToken->1n1gln1azjdzd8cq7lyzy|51c2b342]-AdminTaskTimer" java.lang.OutOfMemoryError: Java heap space
[2023-10-19 09:50:59] [info] #011at java.base/java.util.LinkedList.superClone(LinkedList.java:1012)
[2023-10-19 09:50:59] [info] #011at java.base/java.util.LinkedList.clone(LinkedList.java:1025)
[2023-10-19 09:50:59] [info] #011at com.mchange.v2.resourcepool.BasicResourcePool.cloneOfUnused(BasicResourcePool.java:1856)
[2023-10-19 09:50:59] [info] #011at com.mchange.v2.resourcepool.BasicResourcePool.cullExpired(BasicResourcePool.java:1642)
[2023-10-19 09:50:59] [info] #011at com.mchange.v2.resourcepool.BasicResourcePool.access$1900(BasicResourcePool.java:44)
[2023-10-19 09:50:59] [info] #011at com.mchange.v2.resourcepool.BasicResourcePool$CullTask.run(BasicResourcePool.java:2187)
[2023-10-19 09:50:59] [info] #011at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[2023-10-19 09:50:59] [info] #011at java.base/java.util.TimerThread.run(Timer.java:506)
[2023-10-19 09:50:59] [info] Exception in thread "pool-2-thread-1" java.lang.OutOfMemoryError: Java heap space
[2023-10-19 09:51:03] [crit] [55065ad6-9402-416c-9049-fc067c19c47d][172.16.4.43] FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/pages/error.jsf' will be shown.
[2023-10-19 09:51:03] [crit] java.lang.OutOfMemoryError: Java heap space
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.descriptor.java.JdbcTimestampTypeDescriptor$TimestampMutabilityPlan.deepCopyNotNull(JdbcTimestampTypeDescriptor.java:34)
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.descriptor.java.JdbcTimestampTypeDescriptor$TimestampMutabilityPlan.deepCopyNotNull(JdbcTimestampTypeDescriptor.java:28)
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35)
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:308)
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:304)
[2023-10-19 09:51:03] [crit]     at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:55)
...
```

Output in Kitodo.Production log
```
[WARN] 2023-10-19 09:51:03,869 [http-nio-127.0.0.1-8080-exec-5] org.hibernate.engine.loading.internal.LoadContexts - HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@997b8fc<rs=com.mchange.v2.c3p0.impl.NewProxyResultSet@140d092f [wrapping: null]>
[WARN] 2023-10-19 09:51:03,869 [http-nio-127.0.0.1-8080-exec-5] org.hibernate.engine.loading.internal.CollectionLoadContext - HHH000160: On CollectionLoadContext#cleanup, localLoadingCollectionKeys contained [1] entries
```

Screenshot from out monitoring system
![Screenshot_2023-10-19_09-57-04](https://github.com/kitodo/kitodo-production/assets/2129672/ff0a100e-39c3-4d76-961f-26a5fd6875aa)
which is showing the memory consumption until the error occurs and the Tomcat service must be restarted.

**To Reproduce**
As I already know I did only a reset of 10 processes at once over all necessary eight tasks (and after finishing the reset of 10 processes I logged out to clear the process list (well known bug where the list of processed processes are not cleared until logging out - I forget which issue number it has) and repeated this resetting 4 times without any issue (but with a lot of clicks). On fifth run the Java out of memory error occurs in the middle of resetting between two tasks and I must restart the Tomcat service to get the application working again.

**Expected behavior**
Resetting a lot of processes should not end in Java out of memory error. In 2.x it was possible to reset 100 processes at once over the same workflow / same amount of tasks without any issue.

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Comment by solth** [comment]
Sorry for the stupid question, but what does "resetting" a process mean?

**Comment by henning-gerhardt** [comment]
Resetting a process is meaning: you have a process where all tasks of the corresponding workflow are set on done (whole workflow is finished) and you set all tasks from back to closed except the destination task to open through the action "set process state down" (or so similar, I have currently the application not in front of me). I can add screenshots of this when I'm back on work next week.

**Comment by henning-gerhardt** [comment]
For better understanding of the issue some more explanation with screenshots.

Your task it is to set a lot of processes from a "done" state back to a required open task. F.e. all images of requested processes should be replaced. For this you are searching all this processes by process id and activate the option to show closed processes. A "closed" process looks at SLUB regarding to the workflow like this - for betting understanding the task list view: 

![Screenshot_2023-10-23_08-36-03](https://github.com/kitodo/kitodo-production/assets/2129672/005425d5-3a46-42c6-bc42-3a1cf26df252)

So now you task it is to reset them all the way down to the task "Scannen" where scan operators can replace the images. This is done by the Kitodo action "Set status of process down" as there a lot of  tasks of a lot of processes to work

![Screenshot_2023-10-23_08-39-03](https://github.com/kitodo/kitodo-production/assets/2129672/7e97b7ae-4106-4bfb-9215-28328922fd61)

After stetting down the process state to the required task the workflow now looks like this

![Screenshot_2023-10-23_08-38-20](https://github.com/kitodo/kitodo-production/assets/2129672/514e8829-cac9-4f5c-a31f-edf9ef18a4bd)

This are a lot of clicks to execute this action again and again, but this is maybe an other issue.

Working with correction workflow is no option 
- as we reset more then one process in most cases
- as the starting task of a process is a closed / done task and there is no way to start correction workflows from here
- as the active correction workflows do not allow to start a new "inner" correction workflow

**Comment by BartChris** [comment]
@henning-gerhardt Did you always go over the menu in the process list? Because when you go over the menu in the process detail view and set the status down there: 

<img width="1067" height="407" alt="Image" src="https://github.com/user-attachments/assets/1b6a1fc3-05ed-419b-b6c0-3f69003e48e1" />

A lot less happens. Changing the status in the process list seems to to load workpieces even of unaltered processes (`MetsService.loadWorpiece()` gets called). I suppose the reason is that changing the status of one process leads to an invalidation of the UI and loading of a lot of data.

**Comment by BartChris** [comment]
Changing 

https://github.com/kitodo/kitodo-production/blob/5bf6ff583b0afa1c713fef819465afb176968d09/Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml#L281-L294

to

```xml
 <p:menuitem id="processingStatusUpSelection"
            rendered="#{SecurityAccessController.hasAuthorityToEditTask()}"
            value="#{msgs.processingStatusUp}"
            process="@this"
            action="#{ProcessForm.setTaskStatusUpForSelection}"
            update="@none"
            icon="fa fa-arrow-circle-o-up"/>
<p:menuitem id="processingStatusDownSelection"
            rendered="#{SecurityAccessController.hasAuthorityToEditTask()}"
            value="#{msgs.processingStatusDown}"
            process="@this"
            action="#{ProcessForm.setTaskStatusDownForSelection}"
            update="@none"
            icon="fa fa-arrow-circle-o-down"/>
```

prevents that data for all the other unrelated processes is loaded (Changinge update to `@none`). I i suppose this will improve things. But then the taskstatus of the updated row is not reflected in the UI.

**Comment by BartChris** [comment]
Does the change also adress the memory issues?

Edit: Sorry, i saw you answered that.

**Comment by henning-gerhardt** [comment]
I tried your changes in `3.9.x` and `4.0.x` and I got mixed results: Once the memory peak vor 10 processes was by 5 GB (lower than before with 6.5 GB) but on other only on 3 GB and if I used 30 processes the peak was by 2.5 GB memory usage. It was not possible before to reset the workflow of so many processes since `3.6.x` without killing the application. So this is a good improvement already.

Sometimes after the peak the used memory was released fast but most times it settles down by 50% less. I think that the JVM garbage collector may influence the memory usage more and sometimes less. Influencing the garbage collector should not a way to go as this can have more consequences.

I think your changes and your comment are the right way to puzzle this issue out and solve it.

**Comment by henning-gerhardt** [comment]
I'm not sure about this. So far as I know we have two lists here involved: one is the list from the user which have tasks assigned and the second list is a task which has an user assigned and both lists must be synchronized or one list must be reloaded from the database to get the new values. If you remove the user from the task then you must even remove this task from the user list of assigned tasks. If not the user object can maybe interact with this task which is not assigned anymore or vice versa.
It could even that one or both lists are reloaded in normal use case many times so the not synced lists are synced while working in the application itself and it is maybe here not necessary to sync the lists.

**Comment by thomaslow** [comment]
@henning-gerhardt Currently, we save each bean individually (one after another) in Kitodo.Production. Because of that, there can't really be any conflicts in the data, because for one "save operation" there will always be only one source of truth (that one bean) from the perspective of Hibernate.

In contrast, there can be very complicated scenarios if you "reattach" multiple beans within the same Hibernate session (something we don't do in Kitodo.Production) such that Hibernate would need to figure out which information is the "correct" information, because then those beans could contain conflicting data. Within these scenarios, I think by saying "data gets corrupted" they mean Hibernate doesn't always correctly detect these conflicts and sometimes randomly picks one source of truth and writes it to the database depending on some internal processing order. I don't think there is any risk of the actual database getting corrupted somehow.

Anyway, in Kitodo.Production, I think this problem happens implicitly as well, but is resolved in our own business logic code. If you first save a process, and then save a related task, there is always a specific order to these save operations defined by our code. Because of that, if the information in the task is different from the process, it will overwrite any previous change, without any conflict detection mechanism. And, we make sure that this custom save logic generally works via our integration tests (or Kitodo users).

**Comment by BartChris** [comment]
Since the association of `Task` to `User` does not have `CascadeType.MERGE` or `CascadeType.ALL` annotation there should not be any auto consolidation mechanism in this case if i am not mistaken.

https://github.com/kitodo/kitodo-production/blob/0f1d1c1e120932ae7b5fb08205e9fd5655723628/Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Task.java#L129-L131

> 5. Call session.merge(beans) to reattach modified beans, triggering a complex synchronization logic

As far as i can see we only merging right now in case of `remove`:

https://github.com/kitodo/kitodo-production/blob/0f1d1c1e120932ae7b5fb08205e9fd5655723628/Kitodo-DataManagement/src/main/java/org/kitodo/data/database/persistence/BaseDAO.java#L130

and not in the case of `save`, or?

**Comment by thomaslow** [comment]
> and not in the case of save, or?

I think the deprecated Hibernate "saveOrUpdate" operation (with "CascadeType.SAVE_UPDATE" or "CascadeType.ALL") does a similar thing. It re-attaches the bean and saves any changes to the database.

In recent versions of Hiberante (7+) they dropped "saveOrUpdate" and split the api into `merge` and `persist` to make things more clear to users.

**Comment by BartChris** [comment]
@henning-gerhardt I had another look at this. It seems to me that when setting the status down Hibernate allocates large object graphs which leads to a high memory consumption. I tried to debug what is producing the memory allocation and implemented changes which reduced allocation on my small dataset. 
Maybe you can test if the changes in my branch also have an effect on the memory allocations in your setup:

https://github.com/BartChris/kitodo-production/tree/task_status_memory

When selecting many processes (like 3000 at once) and changing their status, the fact that we load whole processes as `selection` into memory leads to high memory consumption as well. I would therefor first be interested whether my changes lead to improvements when setting down around 10 processes. The huge selection sets should be investigated seperately.

**Comment by henning-gerhardt** [comment]
@BartChris : Thank you. I will look into your changes but it may be take some time.

**Comment by henning-gerhardt** [comment]
Pull request #7174 did even a big improvement. Issue stay open until it is verified on live productive environment that memory usage is on a good level while setting down processes.
