### ISSUE TITLE
MethodNotFoundException when linking to Home Dir

### ISSUE THREAD

**Issue by mSIESTE** [kitodo/kitodo-production#5879]
If i click on "Link Home Dir":
![image](https://github.com/kitodo/kitodo-production/assets/16195237/ec072e7f-8381-4427-a7f8-b1e57bf9e753)
im getting an infinte loading Screen:
![image](https://github.com/kitodo/kitodo-production/assets/16195237/6afcb3dd-1af3-42e2-ba16-aa83e9cbf917)
with this Error Trace:
` javax.el.MethodNotFoundException: Method not found: org.kitodo.production.forms.ProcessForm@42908361.downloadToHome()
             at org.apache.el.util.ReflectionUtil.getMethod(ReflectionUtil.java:296)
             at org.apache.el.parser.AstValue.invoke(AstValue.java:240)
             at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
             at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
             at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
             at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
             at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
             at org.springframework.faces.webflow.FlowActionListener.processAction(FlowActionListener.java:71)
             at org.springframework.faces.model.SelectionTrackingActionListener.processAction(SelectionTrackingActionListener.java:64)
             at javax.faces.component.UICommand.broadcast(UICommand.java:120)
             at javax.faces.component.UIData.broadcast(UIData.java:1732)
             at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
             at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
             at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
             at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
             at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
             at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
             at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
             at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
             at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
             at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:69)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
             at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:86)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
             at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
             at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
             at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
             at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
             at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
             at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
             at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
             at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
             at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
             at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
             at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
             at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
             at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
             at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
             at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
             at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
             at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
             at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
             at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
             at java.lang.Thread.run(Thread.java:748)`

Any idea what Im doing wrong ?

**Comment by solth** [comment]
Which version of Kitodo.Production are you using? Can you verify the `modules` folder (default location is `/usr/local/kitodo/modules`, if not configured differently in your `kitodo_config.properties` file) contains _only_ `*.jar` files with the same version number?

**Comment by mSIESTE** [comment]
Version is 3.1.0 in a docker Container.
My Modules Folder: (contains only 3.1.0.jar files)
![image](https://github.com/kitodo/kitodo-production/assets/16195237/121b3d76-6393-46ea-8918-ac03558ecce5)

**Comment by mSIESTE** [comment]
So everything should be right or not ?

**Comment by solth** [comment]
> So everything should be correct right ?

At least the issue you reported does not stem from a mismatch between web application and module versions. Since Kitodo.Production 3.1.0 is quite old and not supported anymore (see https://github.com/kitodo/kitodo-production/security/policy) it is a little difficult to say what the cause might be. It could be that their was a bug in the "downloadToHome" method, since early 3.x releases were still quite buggy, but I cannot say for sure. Do you have any chance to update your installation to a newer version of Kitodo.Production (the latest release is [3.6.1](https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.6.1))?
