### ISSUE TITLE
Creating import configuration throws NPE

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#6016]
**Describe the bug**
I tried to configure the Kalliope import. This error message occurred when saving. The import configuration was not saved.

```stacktrace
java.lang.NullPointerException
    at org.kitodo.production.forms.validators.ImportConfigurationParentMappingValidator.validate(ImportConfigurationParentMappingValidator.java:51)
    at org.kitodo.production.forms.validators.ImportConfigurationParentMappingValidator.validate(ImportConfigurationParentMappingValidator.java:27)
    at javax.faces.component._ComponentUtils.callValidators(_ComponentUtils.java:291)
    at javax.faces.component.UIInput.validateValue(UIInput.java:489)
    at javax.faces.component.UISelectOne.validateValue(UISelectOne.java:155)
    at org.primefaces.component.selectonemenu.SelectOneMenu.validateValue(SelectOneMenu.java:198)
    at javax.faces.component.UIInput.validate(UIInput.java:746)
    at javax.faces.component.UIInput.processValidators(UIInput.java:293)
    at javax.faces.component.UISelectOne.processValidators(UISelectOne.java:117)
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1458)
    ...
```

**To Reproduce**
1. Fill in data, see screenshots below
2. Click on 'Save'
3. See error

**Expected behavior**
The process should be saved, or an understandable error message should appear if there is a problem.

**Release**
3.6.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 124.0.1

**Additional context**
![page1](https://github.com/kitodo/kitodo-production/assets/3040657/b65fd201-afb6-45e9-a830-b821e57d891e)
![page2](https://github.com/kitodo/kitodo-production/assets/3040657/6bde3b2a-f27e-4976-aa4b-34ae244916de)

**Comment by BartChris** [comment]
Maybe related: https://github.com/kitodo/kitodo-production/issues/5647
