### ISSUE TITLE
Stack trace if ruleset cannot be loaded

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#6165]
If the ruleset cannot be loaded (i.e. if there is a typo in the XML, and it is syntactically invalid) a stack trace is shown, that also hides the error message.

Stack trace:

    java.lang.NullPointerException
        at org.kitodo.production.forms.createprocess.AddMetadataDialog.prepareAddableMetadataForStructure(AddMetadataDialog.java:78)
        at org.kitodo.production.forms.createprocess.AddMetadataDialog.metadataAddableToStructureElement(AddMetadataDialog.java:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...

**Comment by solth** [comment]
@matthias-ronge please use the issue template and specify how to reproduce this error. Does it occur when opening a process in the metadata editor?

**Comment by matthias-ronge** [comment]
I.e., have a typo like this in your ruleset:

    <labe>Title</label>

**Comment by henning-gerhardt** [comment]
As a side note which can be moved into an own issue: we should think about in a long term thinking if it would not better to use at least a basic XML validation on accessing any XML file (meta data file, ruleset files, xslt files, ...) and report any issue found there before any future program code is using an invalid XML file?
