### ISSUE TITLE
SpracheForm.locale null

### ISSUE THREAD

**Issue by atiro** [kitodo/kitodo-production#719]
Have installed following instruction in READ . Going to homepage redirects to Main.jsf which throws a server error:

03-Apr-2017 17:05:59.168 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
 java.lang.IllegalArgumentException: Locale or String class expected. Expression: #{SpracheForm.locale}. Return value null
        at org.apache.myfaces.taglib.core.ViewTag.setProperties(ViewTag.java:227)
        at javax.faces.webapp.UIComponentTag.findComponent(UIComponentTag.java:539)
        at javax.faces.webapp.UIComponentTag.doStartTag(UIComponentTag.java:315)
        at org.apache.myfaces.taglib.core.ViewTag.doStartTag(ViewTag.java:73)
        at org.apache.jsp.newpages.error_jsp._jspService(error_jsp.java:287)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:401)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:345)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

Seems like locale/language not being set? (or possibly an earlier error causing session problems?), I have edited the config file to force language to 'en' so not sure where else it is looking for. Running tomcat8 and openjdk-8.

**Comment by henning-gerhardt** [comment]
Just two questions:
- Which version did you use?
- Did you follow the [German installion guide](https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung) for your installed version?

**Comment by henning-gerhardt** [comment]
README contains only a very basic installation guide for developers. 

You should use the installation guide (link is in my first comment) and I recommend to use the last release [Kitodo.Production 2.0.0](https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-2.0.0) and not a build from master branch as there are many changes inside and master branch is not stable at the moment.

**Comment by atiro** [comment]
Will do, thanks!
