### ISSUE TITLE
Closing step through ActiveMQ is failing

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#755]
Sometimes a step should be closed through ActiveMQ stay in state "open". A log error message appears:

```
ERROR 2017-04-21 11:06:14,540 (StepManager.java:getStepById:32)
        Cannot not load step with id 746030
java.sql.SQLException: Already closed.
    at org.apache.commons.dbcp.PoolableConnection.close(PoolableConnection.java:114)
    at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.close(PoolingDataSource.java:191)
    at de.sub.goobi.persistence.apache.MySQLHelper.getConnection(MySQLHelper.java:52)
    at de.sub.goobi.persistence.apache.MySQLHelper.getStepByStepId(MySQLHelper.java:183)
    at de.sub.goobi.persistence.apache.StepManager.getStepById(StepManager.java:30)
    at de.sub.goobi.forms.AktuelleSchritteForm.SchrittDurchBenutzerAbschliessen(AktuelleSchritteForm.java:517)
    at org.goobi.mq.processors.FinaliseStepProcessor.process(FinaliseStepProcessor.java:64)
    at org.goobi.mq.ActiveMQProcessor.onMessage(ActiveMQProcessor.java:103)
    at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1230)
    at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:134)
    at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:205)
    at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:127)
    at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

```

This happens on regular work time so a database connection should be open and there are not too much open database connections at this time. 

Manually closing this step does work around this problem.

Affected version: Kitodo.Production 2.0.0 

Edit: this could even happen on older versions as we found open steps from former version.

**Comment by henning-gerhardt** [comment]
As far as I can say now that this error occurs if two or more steps should be closed in a short time frame (in one or two seconds). 

I don't know if there is a sequential or parallel execution of closing step code. It looks for me like a parallel execution and in this is one database connection closed while a other execution is working with this database connection. 

Maybe the main fault is in the [MySQL helper](https://github.com/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/persistence/apache/MySQLHelper.java) method [getConnection](https://github.com/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/persistence/apache/MySQLHelper.java#L44-L81) as this not programmed in a thread safe way.

**Comment by matthias-ronge** [comment]
Technically, the problem originates from Hibernate, when trying to access the step’s ID in [`AktuelleSchritteForm` line 517](https://github.com/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/forms/AktuelleSchritteForm.java#L517):

    StepObject so = StepManager.getStepById(this.mySchritt.getId());
                                                           ^^^^^^^

The object `mySchritt` is a Hibernate proxy object which is linked with a Hibernate session that is already closed. Chances are that this is caused by `session.close();` statement in [`BaseDAO` line 108](https://github.com/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/persistence/BaseDAO.java#L108) which happens only if there is no session.

**Comment by matthias-ronge** [comment]
My first guess was wrong. The problem is in [`MySQLHelper` line 52](https://github.com/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/persistence/apache/MySQLHelper.java#L52) which closes an invalid session without probing if it is aready closed, and causes an error if it already is.

**Comment by henning-gerhardt** [comment]
Your change looks good, @matthias-ronge I could not reproduce this issue on my local development system as  this kind of error happen to randomly. I will close this issue until we are discover this issue again.
